<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<org.eventb.theory.core.scTheoryLanguageRoot org.eventb.core.accurate="true" org.eventb.core.configuration="org.eventb.theory.core.tul" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul">
<org.eventb.theory.core.scAvailableTheoryProject name="'" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#'" org.eventb.theory.core.availableTheoryProject="/theory-axiom-reals">
<org.eventb.theory.core.scAvailableTheory name="THYPH_0" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#'|org.eventb.theory.core.availableTheory#(" org.eventb.theory.core.availableTheory="/theory-axiom-reals/Intervals.dtf|org.eventb.theory.core.deployedTheoryRoot#Intervals"/>
<org.eventb.theory.core.scAvailableTheory name="THYPH_1" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#'|org.eventb.theory.core.availableTheory#)" org.eventb.theory.core.availableTheory="/theory-axiom-reals/DiffEq.dtf|org.eventb.theory.core.deployedTheoryRoot#DiffEq"/>
</org.eventb.theory.core.scAvailableTheoryProject>
<org.eventb.theory.core.scAvailableTheoryProject name="(" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#(" org.eventb.theory.core.availableTheoryProject="/ex-heating-continuous">
<org.eventb.theory.core.scAvailableTheory name="THYPH_0" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#(|org.eventb.theory.core.availableTheory#'" org.eventb.theory.core.availableTheory="/ex-heating-continuous/Temperature.dtf|org.eventb.theory.core.deployedTheoryRoot#Temperature"/>
<org.eventb.theory.core.scAvailableTheory name="THYPH_1" org.eventb.core.source="/ex-heating-continuous/TheoryPath.tul|org.eventb.theory.core.theoryLanguageRoot#TheoryPath|org.eventb.theory.core.availableTheoryProject#(|org.eventb.theory.core.availableTheory#(" org.eventb.theory.core.availableTheory="/ex-heating-continuous/TemperatureExtra.dtf|org.eventb.theory.core.deployedTheoryRoot#TemperatureExtra"/>
</org.eventb.theory.core.scAvailableTheoryProject>
</org.eventb.theory.core.scTheoryLanguageRoot>
